# 定义 Gitpod 运行的基础镜像（这里我们使用 Python 官方镜像）
image: python:3.10

# 任务（Tasks）：初始化依赖 & 启动开发工具
tasks:
  - name: Install dependencies
    init: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "✅ Python dependencies installed"
    command: |
      echo "Starting development server..."
  - name: Start Flask Server
    command: python app.py

  - name: Start Jupyter Notebook
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

# 端口（Ports）：开放 Flask 和 Jupyter Notebook 端口
ports:
  - port: 5000
    onOpen: open-preview  # 打开 Flask 预览页面
  - port: 8888
    onOpen: open-browser  # 打开 Jupyter Notebook

# 自动安装 VS Code 扩展
vscode:
  extensions:
    - ms-python.python          # Python 扩展
    - ms-toolsai.jupyter        # Jupyter Notebook 支持
    - ms-pyright.pyright        # Python 代码检查

# Gitpod 启动时自动执行的命令
startupTasks:
  - name: Verify Environment
    command: |
      python --version
      pip freeze

# 自定义存储（Gitpod 关闭后仍然保持的数据）
gitpod:
  dockerfile: Dockerfile
  workspaceMounts:
    - mountPath: /workspace
      persistence: true
